### ISSUE TITLE
On first load - the menu goes into place

### ISSUE THREAD

**Issue by iamrobert** [michaeljoyner/michaeljoyner.github.io#4]
On the first load - you see the menus fly up into place:

https://www.youtube.com/watch?v=CJMbwNlBUi4

Its the white boxes - perhaps a hide until load class....

**Comment by michaeljoyner** [comment]
Thanks, will do that soon.

**Comment by michaeljoyner** [comment]
I have done as you suggested (hiding until loaded). Please can you verify and let me know. Thanks.

**Comment by iamrobert** [comment]
Fixed.

It also does it on resizing from mobile to desktop. But I guess that's only something developers do...

**Comment by michaeljoyner** [comment]
Ya, changing from desktop to mobile isn't really a common use case, and it would be tricky to disable transitions just got that case.
