### ISSUE TITLE
How to change page meta description?

### ISSUE THREAD

**Issue by iamrobert** [michaeljoyner/michaeljoyner.github.io#5]
https://github.com/iamrobert/iamrobert.github.io/blob/master/_tutorials/example-article.md

I'm still seeing wide:
![image](https://user-images.githubusercontent.com/8617673/37161204-031db180-232d-11e8-8ca6-e08945f4dcd3.png)

**Comment by michaeljoyner** [comment]
Thanks for reminding me about that. We need a description for the site in general (English and German). For the individual pages/articles they should include the description with the information in the "front matter". I must also remember to take out the open sans font link.

**Comment by michaeljoyner** [comment]
The site description needs to be set still (I guess they will supply it, or at least the German). The homepage will use the site description. For articles, they should add the description in the front matter (I will include in docs). If no description is added, it will then try take an excerpt from the page, and failing that will fall back to the site description.
