### ISSUE TITLE
Client want extra level menu hidden

### ISSUE THREAD

**Issue by iamrobert** [michaeljoyner/michaeljoyner.github.io#6]
Hi Michael,

The client wants the extra level menu hidden. 

As I requested this - we'll pay for the extra time required on this if you've exceeded your total. 

![img](https://i.imgur.com/3vSJYDw.png)

Also - for the sub menu - I think hide text for the "X": 
![img](https://i.imgur.com/3f3F0ST.png)

I think in the accordion it can remain fully visible.

**Comment by michaeljoyner** [comment]
Alright, will do. It definitely will exceed time, so I'll keep track of that. Before I start, some questions:

In the desktop dropdown, what is the expected behavior for exposing the hidden third level? Out to the side?

In the mobile form of the menu, what is expected? Also hidden? If so, accordion type reveal or a whole new panel (which seems a but ridiculous)

**Comment by iamrobert** [comment]
1. Out to the side 
2. 
a) side Scroll
https://codyhouse.co/demo/mega-dropdown/index.html#0
![img](https://i.imgur.com/3WBlGxX.png)

which I guess is kinda like a whole new panel... 

So - if its easier to mimic existing panel - do it that way.

**Comment by iamrobert** [comment]
actually would it be simpler to make both desktop and mobile the side
scroll accordion:

https://codyhouse.co/demo/mega-site-navigation/index.html#0

That could work as well.


Robert Stark
Web + Graphic Designer
http://www.iamrobert.com
0918 44 88 24 || +886 (4) 2452 1322

**Comment by michaeljoyner** [comment]
The structure of their menu doesn't really fit the second example, seeing as they have many top level items and very few third level items. But maybe I am missing something. You can just let me know which one you prefer and I'll do it. As I currently understand it, the first option will be quicker.

**Comment by iamrobert** [comment]
I was thinking about it hitting the edge of the page - if it flies out from the side on smaller screens on desktop. Not sure - if there is edge detection built in your menu.

Option 1 - then.

**Comment by michaeljoyner** [comment]
I have put up a possible new version, have a look when you get the time. Thanks.

**Comment by iamrobert** [comment]
OK - I will submit it for feedback.

I am not sure that the 100% height/width on desktop will be positive.

However will sell it that as users need to scan through a list of
complicated terms - it reduces distraction.

The one thing that could be improved - is when you:

1. Tutorials > Xtra Menu
2. Close Tutorials
3. Reopen Tutorials - the Xtra Menu slides away

On close remove the  exposed - class would probably work.

Also could we add a custom scroll bar.

/* *
======================================================================= +
BROWSER SCROLL BAR *
======================================================================= */
::-webkit-scrollbar { width: 8px; height: 8px; -webkit-border-radius: 0px;
border-radius: 0px; } ::-webkit-scrollbar-button { width: 0px; height: 0px;
} ::-webkit-scrollbar-thumb { background: #c1c1c1; border: 0px none
#ffffff; border-radius: 0px; } ::-webkit-scrollbar-thumb:hover {
background: #a8a8a8; } ::-webkit-scrollbar-thumb:active { background:
#787878; } ::-webkit-scrollbar-track { background: #f1f1f1; border: 0px
none #ffffff; border-radius: 0px; } ::-webkit-scrollbar-track:hover {
background: #f1f1f1; } ::-webkit-scrollbar-track:active { background:
#f1f1f1; } ::-webkit-scrollbar-corner { background: transparent; display:
none; height: 0px; width: 0px; }

**Comment by michaeljoyner** [comment]
Ya, the full page thing isn't perfect, but it solves a lot of the problems we have from there being so many unknowns involved (how high the menus and submenus will be, screen sizes, etc). Anyway, let's see what they say. I am open to suggestions.

I'll add the scrollbar.

**Comment by michaeljoyner** [comment]
Okay, here is a slightly altered version, without the full screen height. 

https://www.youtube.com/watch?v=tdOiJnNdz4k

If you think it would be better I will make the changes for real and push them up.

**Comment by iamrobert** [comment]
Unfortunately - it doesn't work for the client.

I also don't feel that video will get to where he is satisfied with. As the height shouldn't scroll.


_thanks for the update.

I have the feeling that the full screen is a bit too much.

Can we revert it back to the non-full but with the collapsed third level?_

I feel he wants a standard menu for desktop:
https://foundation.zurb.com/building-blocks/blocks/foundation-5-top-bar.html

https://codepen.io/arjunamgain/pen/YXBeLJ

Perhaps if you can give me some examples of what you're trying to build - then I can sell it.

I'll be around tomorrow if you want to skype.

**Comment by michaeljoyner** [comment]
Alright, that is all fine. Maybe to save time, just tell me what to do and I'll just do it. The problem, as far as I see it, is that they are trying to fit in an entire table of contents as a nav menu, which has its issues.

One problem is that the names of each item vary greatly in length, and can be quite long, whereas most traditional menus generally have shorter names.

Another problem is that the structure is fairly simple, meaning we can't really do a "mega menu" style thing with a single dropdown broken into further categories.

That being said, it sounds like they just want a dropdown menu, so maybe I should just make a dropdown menu in the traditional manner, for better or worse. If item names are too long it will just break into a second line. The third level can just open to whichever side makes sense.

Does the mobile version need to change?

**Comment by iamrobert** [comment]
Hi Michael,

I do understand your points.

So - I think a standard drop down menu that expands out like the zurb
example would work. Or like your old menu with a hover left or right.

At the moment mobile version doesn't need to change.

I think the 3rd level is somewhere in the middle of the nav - so it should
be ok width wise.

Thanks

**Comment by michaeljoyner** [comment]
Hi Robert

I have put up another version of the menu for you to consider. Please could you take a look and let me know.

**Comment by iamrobert** [comment]
Hi Michael,

Awesome - That's moving in the right direction.

I think the only thing is the hover state should be on permanently on the top level - even if your mouse is outside. Like bootstrap - the grey is on consistently.

https://codepen.io/ajaypatelaj/pen/prHjD

Otherwise I'm not sure why the menu is still open when I hover off.

https://i.imgur.com/XiiMXCc.png

**Comment by iamrobert** [comment]
The second issue - is the menu should hide until its all loaded - as I'm clicking and as the 2nd level hasn't loaded - nothing has happened.

**Comment by iamrobert** [comment]
Also bug in mobile which I have confirmed.

_But I found a weird effect in the mobile version:

From the homepage go to video tutorials -> Tutorial five, Then click on the menu again and then some (but not all) of the first level menu items are not clickable anymore (e.g. Tutorials and Data sources). Can you reproduce this effect?_

**Comment by michaeljoyner** [comment]
Hi Robert

Glad you think it is moving in the right direction. I'm aware there are several more detailed issues (hover states, etc) to be worked out, but for now I need to know whether the idea of the third level sliding in as opposed to coming out the side is acceptable or not. Once that is all decided we can finish off all the details such as hover states, etc.

The menu now operates on click as opposed to hover (like bootstrap), which I do think is a better idea, but that's just my personal preference. If you want it to operate on hover alone, it can be done. If we stick with clicks, I will add the listeners to handle clicking outside the menu to close, etc.

For the second issue above, I'm not sure if I follow, but the menu is hidden until the page loads (see #4 ). There is an issue of the size of the font files (over 1MB) which we need to address, as it results in a very slow load time for slower connections).

**Comment by iamrobert** [comment]
I like the click as the pages don't exist. I like the menu and will send to
the client for feedback.

The top level is clickable - but nothing happens on the drop down:

https://www.youtube.com/watch?v=t1dZT2NmN6A

So hiding the menu and the SVG arrows until load would make a greater
experience.

Not sure why the font files are so large. I usually use this to output my
files:

https://fontie.flowyapps.com/home

Perhaps the fonts have additional character sets.

Also - the client wants to use:

Helvetica Neue Regular for the body copy and not medium as feels its too
bold.

**Comment by michaeljoyner** [comment]
Okay, I'll wait until I hear further about the menu before I do anything with it. I'll try sort out the fonts in the meantime.

**Comment by iamrobert** [comment]
Sweet - Menu is going well - just those 2 issues...

_Yes, the click is fine with me.

It’s great now!_

**Comment by michaeljoyner** [comment]
So I can proceed? The fonts have been updated, and the medium has been swapped out for the regular. That font file generator is an awesome resource, thanks! Has made a big difference to the speed of the site.

**Comment by iamrobert** [comment]
Can proceed on menu...

**Comment by michaeljoyner** [comment]
I have set the hover state to remain as long as the dropdown is open, and clicking outside of the dropdown will close the menu. Are there any remaining issues with the menu, or any styling changes you'd like done?

**Comment by iamrobert** [comment]
I think we're good Michael. Can u email me with the additional hours.
